on:
  push:
    branches: [master]
    tags: "*"
  pull_request:
    # Check all PR

jobs:
  build-manylinux-wheels:
    runs-on: ubuntu-20.04
    name: x86_64 manylinux2010
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: build wheels
        run: |
          pip install wheel
          pip wheel --no-deps -w dist .

      - uses: actions/checkout@v3
        with:
          ref: wheels
          fetch-depth: 2
      - run: |
          git checkout HEAD^
          git config user.name github-actions
          git config user.email github-actions@github.com
          mv dist/*whl .
          git add ./*whl
          git commit -m "generated"
          git push -f
