on:
  push:
    branches: [master]
    tags: "*"

jobs:
  build-manylinux-wheels:
    runs-on: ubuntu-20.04
    name: x86_64 manylinux2010
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: build wheels
        run: |
          pip install wheel
          pip wheel --no-deps -w dist .
          git checkout wheels
          git reset --hard HEAD^
          mv dist/*whl .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./*whl
          git commit -m "generated"
          echo ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: wheels
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
