on:
  push:
    branches: [master]
    tags: "*"
  pull_request:
    # Check all PR

jobs:
  build-manylinux-wheels:
    runs-on: ubuntu-20.04
    name: x86_64 manylinux2010
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: build wheels
        run:
          pip install wheel
          pip wheel --no-deps -w dist .
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*.whl
      - name: upload wheels to GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          path: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
